Repository rust-embedded/embedded-hal, pull requests merged in 2020-09, with the labels that each got.

#239 Add try_set_state method for OutputPin
  CHANGELOG.md
  src/digital.rs
Labels: proposal

#120 Document implicit assumption in non-blocking spi trait
  src/spi.rs
Labels: S-waiting-on-author, T-hal

#170 Remove unsupported examples for hal
  Cargo.toml
  src/lib.rs
Labels: S-waiting-on-review, T-hal
